In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [65]:
a=pd.concat([x,y,z],axis=0)

In [66]:
a.drop('Total_Charge',axis=1,inplace=True)

In [69]:
a.rename(columns={'Total_charge':'Expected_charges'},inplace=True)

Orders where X has been charged correctly

In [71]:
a[a['Difference']==0]

,Order ID,SKU,Order Qty,AWB Code,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.),Weight_kg,Weight_Slab,Expected_charges,Difference
25,2001808585,8904223818706,1.0,1091117436652,0.72,121003,175101,b,Forward charges,61.3,0.127,0.5,61.3,0.0
27,2001808507,8904223818706,1.0,1091117436383,0.79,121003,208002,b,Forward charges,61.3,0.127,0.5,61.3,0.0
34,2001807814,8904223818706,1.0,1091117326612,0.79,121003,284001,b,Forward charges,61.3,0.127,0.5,61.3,0.0
49,2001806575,8904223818706,1.0,1091117225016,0.68,121003,248001,b,Forward charges,61.3,0.127,0.5,61.3,0.0
50,2001806547,8904223818706,1.0,1091117224611,1.00,121003,283102,b,Forward charges,61.3,0.127,0.5,61.3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2001811363,8904223815873,1.0,1091117958395,0.59,121003,321608,d,Forward charges,90.2,0.065,0.5,90.2,0.0
368,2001807960,8904223819505,1.0,1091117327312,1.00,121003,485001,d,Forward charges,90.2,0.210,0.5,90.2,0.0
370,2001811229,8904223819345,1.0,1091117957942,0.60,121003,324001,d,Forward charges,90.2,0.165,0.5,90.2,0.0
377,2001808801,8904223815866,2.0,1091117437680,0.80,121003,335001,d,Forward charges,90.2,0.113,0.5,90.2,0.0
379,2001808801,8904223815682,1.0,1091117437680,0.80,121003,335001,d,Forward charges,90.2,0.210,0.5,90.2,0.0

Orders where X has been overly charged

In [72]:
a[a['Difference']<0]

,Order ID,SKU,Order Qty,AWB Code,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.),Weight_kg,Weight_Slab,Expected_charges,Difference
0,2001827036,8904223818706,1.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,0.127,0.5,61.3,-56.6
18,2001809592,8904223818706,1.0,1091117616121,1.50,121003,244713,b,Forward charges,89.6,0.127,0.5,61.3,-28.3
31,2001807956,8904223818706,1.0,1091117327275,1.08,121003,248006,b,Forward charges,89.6,0.127,0.5,61.3,-28.3
45,2001806776,8904223818706,1.0,1091117227573,2.86,121003,226004,b,Forward charges,174.5,0.127,0.5,61.3,-113.2
59,2001827036,8904223819093,1.0,1091122418320,1.60,121003,173213,b,Forward charges,117.9,0.150,0.5,61.3,-56.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,2001807328,8904223818997,1.0,1091117324346,2.28,121003,335502,d,Forward charges,224.6,0.490,0.5,90.2,-134.4
397,2001806567,8904223815804,1.0,1091117224902,1.16,121003,370201,d,Forward charges,135.0,0.160,0.5,90.2,-44.8
398,2001806567,8904223818577,1.0,1091117224902,1.16,121003,370201,d,Forward charges,135.0,0.150,0.5,90.2,-44.8
399,2001806408,8904223819437,2.0,1091117222931,2.50,121003,532484,d,Forward charges,224.6,0.552,1.5,90.2,-134.4
400,2001806232,8904223818645,6.0,1091117222124,1.30,121003,507101,d,Forward charges,135.0,0.137,1.0,90.2,-44.8

Orders where X has been under charged

In [73]:
a[a['Difference']>0]

,Order ID,SKU,Order Qty,AWB Code,Charged Weight,Warehouse Pincode,Customer Pincode,Zone,Type of Shipment,Billing Amount (Rs.),Weight_kg,Weight_Slab,Expected_charges,Difference
2,2001819252,8904223818706,1.0,1091120352712,0.3,121003,174101,b,Forward charges,33.0,0.127,0.5,61.3,28.3
9,2001811475,8904223818706,1.0,1091121844806,0.5,121003,173212,b,Forward charges,33.0,0.127,0.5,61.3,28.3
79,2001819252,SACHETS001,1.0,1091120352712,0.3,121003,174101,b,Forward charges,33.0,0.010,0.5,61.3,28.3
109,2001811475,8904223818669,1.0,1091121844806,0.5,121003,173212,b,Forward charges,33.0,0.240,0.5,61.3,28.3
118,2001812838,8904223819031,4.0,1091118547832,0.6,121003,262405,b,Forward and RTO charges,102.3,0.112,0.5,110.1,7.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,2001818390,8904223818683,1.0,1091120014461,0.8,121003,783301,e,Forward and RTO charges,213.5,0.121,0.5,218.3,4.8
288,2001818390,8904223819147,1.0,1091120014461,0.8,121003,783301,e,Forward and RTO charges,213.5,0.240,0.5,218.3,4.8
304,2001818390,8904223818935,4.0,1091120014461,0.8,121003,783301,e,Forward and RTO charges,213.5,0.120,0.5,218.3,4.8
383,2001808295,8904223819161,1.0,1091117435661,0.2,121003,673002,e,Forward and RTO charges,107.3,0.115,0.5,218.3,111.0
387,2001808295,8904223819260,1.0,1091117435661,0.2,121003,673002,e,Forward and RTO charges,107.3,0.130,0.5,218.3,111.0